[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.15"

[features]
resolution = true
skip-lint = false

[programs.devnet]
marginfi = "BaHsySqRkUu7j2CRq73kCapzzP6GnwWtbYGazmAnmrDr"

[programs.localnet]
liquidity_incentive_program = "8weyHdR5fZQHhjhNmpYL2p7zGJhFfybyLUJQ82SyZd7s"
marginfi = "BaHsySqRkUu7j2CRq73kCapzzP6GnwWtbYGazmAnmrDr"
mocks = "2KmpyMMu2bcs749NK2eEYV1sU342XRErR5WytdvonKfC"

[programs.mainnet]
liquidity_incentive_program = "8weyHdR5fZQHhjhNmpYL2p7zGJhFfybyLUJQ82SyZd7s"
marginfi = "BaHsySqRkUu7j2CRq73kCapzzP6GnwWtbYGazmAnmrDr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.spec.ts --exit --require tests/rootHooks.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "DeyH7QxWvnbbaVB4zFrf4hoq7Q8z1ZT14co42BGwGtfM"
filename = "tests/fixtures/bonk_bank.json"

[[test.validator.account]]
address = "4kNXetv8hSv9PzvzPZzEs1CTH6ARRRi2b8h6jk1ad1nP"
filename = "tests/fixtures/cloud_bank.json"

[[test.validator.account]]
address = "8FRFC6MoGGkMFQwngccyu69VnYbzykGeez7ignHVAFSN"
filename = "tests/fixtures/localnet_usdc.json"
